# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetrisksetCSF <- function(cdata) {
    .Call(`_iCenJMH_GetrisksetCSF`, cdata)
}

OLS <- function(X, Y) {
    .Call(`_iCenJMH_OLS`, X, Y)
}

MultVV <- function(x, y) {
    .Call(`_iCenJMH_MultVV`, x, y)
}

MultVVoutprod <- function(x) {
    .Call(`_iCenJMH_MultVVoutprod`, x)
}

MultVV2outprod <- function(x, y) {
    .Call(`_iCenJMH_MultVV2outprod`, x, y)
}

MultVVinprod <- function(x) {
    .Call(`_iCenJMH_MultVVinprod`, x)
}

CH <- function(H, t) {
    .Call(`_iCenJMH_CH`, H, t)
}

HAZ <- function(H, t) {
    .Call(`_iCenJMH_HAZ`, H, t)
}

MultMM <- function(x, y) {
    .Call(`_iCenJMH_MultMM`, x, y)
}

getCovSF <- function(beta, tau, gamma1, alpha1, vee1, H01, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, FUNENW, FUNBENW, FUNBS, FUNBW, FUNWS, FUNBSENW, FUNEC, FUNBEC, FUNBSEC, FUNWEC, FUNWSEC, FUNB, FUNW) {
    .Call(`_iCenJMH_getCovSF`, beta, tau, gamma1, alpha1, vee1, H01, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, FUNENW, FUNBENW, FUNBS, FUNBW, FUNWS, FUNBSENW, FUNEC, FUNBEC, FUNBSEC, FUNWEC, FUNWSEC, FUNB, FUNW)
}

getECSF <- function(beta, tau, gamma1, alpha1, vee1, H01, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, xsmatrix, wsmatrix, CUH01, HAZ01) {
    .Call(`_iCenJMH_getECSF`, beta, tau, gamma1, alpha1, vee1, H01, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, xsmatrix, wsmatrix, CUH01, HAZ01)
}

getHazardSF <- function(CumuH01, survtime, cmprsk, H01, CUH01, HAZ01) {
    .Call(`_iCenJMH_getHazardSF`, CumuH01, survtime, cmprsk, H01, CUH01, HAZ01)
}

getMCSF <- function(beta, tau, gamma1, alpha1, vee1, H01, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, FUNENW, FUNBENW, FUNBS, FUNBW, FUNWS, FUNBSENW, FUNEC, FUNBEC, FUNBSEC, FUNWEC, FUNWSEC, FUNB, FUNW) {
    .Call(`_iCenJMH_getMCSF`, beta, tau, gamma1, alpha1, vee1, H01, Sig, Z, X1, W, Y, X2, survtime, cmprsk, mdata, mdataS, FUNENW, FUNBENW, FUNBS, FUNBW, FUNWS, FUNBSENW, FUNEC, FUNBEC, FUNBSEC, FUNWEC, FUNWSEC, FUNB, FUNW)
}

