# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetrisksetC <- function(cdata) {
    .Call(`_iCenJMH_GetrisksetC`, cdata)
}

GetrisksetS <- function(iCendata) {
    .Call(`_iCenJMH_GetrisksetS`, iCendata)
}

OLS <- function(X, Y) {
    .Call(`_iCenJMH_OLS`, X, Y)
}

MultVV <- function(x, y) {
    .Call(`_iCenJMH_MultVV`, x, y)
}

MultVVoutprod <- function(x) {
    .Call(`_iCenJMH_MultVVoutprod`, x)
}

MultVV2outprod <- function(x, y) {
    .Call(`_iCenJMH_MultVV2outprod`, x, y)
}

MultVVinprod <- function(x) {
    .Call(`_iCenJMH_MultVVinprod`, x)
}

CH <- function(H, t) {
    .Call(`_iCenJMH_CH`, H, t)
}

HAZ <- function(H, t) {
    .Call(`_iCenJMH_HAZ`, H, t)
}

MultMM <- function(x, y) {
    .Call(`_iCenJMH_MultMM`, x, y)
}

updatePSLR <- function(YS, mdata, mdataS, idsum) {
    .Call(`_iCenJMH_updatePSLR`, YS, mdata, mdataS, idsum)
}

GetCov <- function(S) {
    .Call(`_iCenJMH_GetCov`, S)
}

GetSE <- function(nbeta, ntau, nSig, ngamma, nalpha, Cov) {
    .Call(`_iCenJMH_GetSE`, nbeta, ntau, nSig, ngamma, nalpha, Cov)
}

getEC <- function(beta, tau, gamma, alpha, H0Y, Sig, X1, Z, W, Y, X2, survtime, status, ni, nt, xsmatrix, wsmatrix, pSLR, Psl, FUNENW, FUNEBNW, FUNEBSNW, FUNE, FUNBW, FUNBWE, FUNBWSE, FUNBWS, pStol) {
    .Call(`_iCenJMH_getEC`, beta, tau, gamma, alpha, H0Y, Sig, X1, Z, W, Y, X2, survtime, status, ni, nt, xsmatrix, wsmatrix, pSLR, Psl, FUNENW, FUNEBNW, FUNEBSNW, FUNE, FUNBW, FUNBWE, FUNBWSE, FUNBWS, pStol)
}

getES <- function(beta, tau, gamma, alpha, Sig, Z, X1, W, Y, X2, obstime, xsmatrix, wsmatrix, pSLR, Si, CH0s, CH0u, indexX, indexW) {
    .Call(`_iCenJMH_getES`, beta, tau, gamma, alpha, Sig, Z, X1, W, Y, X2, obstime, xsmatrix, wsmatrix, pSLR, Si, CH0s, CH0u, indexX, indexW)
}

getGradT <- function(gamma, alpha, H0, X2, survtime, status, ni, nt, PslT, FUNE, FUNBW, FUNBWE) {
    .Call(`_iCenJMH_getGradT`, gamma, alpha, H0, X2, survtime, status, ni, nt, PslT, FUNE, FUNBW, FUNBWE)
}

getGradY <- function(beta, tau, Sig, Z, X1, W, Y, ni, nt, Psl, FUNENW, FUNEBNW, FUNEBSNW, FUNBWS, pStol) {
    .Call(`_iCenJMH_getGradY`, beta, tau, Sig, Z, X1, W, Y, ni, nt, Psl, FUNENW, FUNEBNW, FUNEBSNW, FUNBWS, pStol)
}

getGradS <- function(Psl2, nt, pStol, GradS) {
    .Call(`_iCenJMH_getGradS`, Psl2, nt, pStol, GradS)
}

getHazard <- function(CumuH0, survtime, status, H0, CUH0, HAZ0) {
    .Call(`_iCenJMH_getHazard`, CumuH0, survtime, status, H0, CUH0, HAZ0)
}

getMC <- function(beta, tau, gamma, alpha, H0, Sig, Z, X1, W, Y, X2, survtime, status, ni, nt, Psl, PslT, FUNENW, FUNEBNW, FUNEBSNW, FUNE, FUNBW, FUNBWE, FUNBWSE, FUNBWS, pStol) {
    .Call(`_iCenJMH_getMC`, beta, tau, gamma, alpha, H0, Sig, Z, X1, W, Y, X2, survtime, status, ni, nt, Psl, PslT, FUNENW, FUNEBNW, FUNEBSNW, FUNE, FUNBW, FUNBWE, FUNBWSE, FUNBWS, pStol)
}

